<?php /** @var $this Styla_Connect_Block_Adminhtml_Hint_Environment */ ?>

<?php if($this->userNeedsToRegister()): ?>
    <div class="section-config notification-global">
        <strong><?php echo $this->__('Warning: You need to connect your store with Styla.') ?></strong>
        <p><?php echo $this->__('Before you can use the module in this mode (stage/ production), you must send activation data in order to connect with Styla. Please do it now.') ?></p>
        
        <p><?php echo $this->__('Please click here to connect your store with Styla') ?>: <a href="<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/styla_api/index') ?>"><?php echo $this->__('click here to connect.') ?></a></p>
    </div>
<?php endif; ?>