<div class="section-config">
    <div class="entry-edit-head">
        <span><a href="#"><?php echo $this->__('Currently Used Configuration') ?></a></span>
    </div>
    <fieldset>
        <div class="section-config">
            <div class="entry-edit-head">
                <span><?php echo $this->__('Default') ?></span>
            </div>
            <fieldset>
                <strong>Stage:</strong>
                <?php echo $this->getConfiguration('stage', null, null) ?>
                <strong>Production:</strong>
                <?php echo $this->getConfiguration('prod', null, null) ?>

                <?php foreach($this->getWebsites() as $website): ?>
                    <div class="section-config">
                        <div class="entry-edit-head">
                            <span><?php echo $this->__('Website') ?>: <?= $website->getName() ?></span>
                        </div>
                        <fieldset>
                            <strong>Stage:</strong>
                            <?php echo $this->getConfiguration('stage', $website->getCode(), null) ?>
                            <strong>Production:</strong>
                            <?php echo $this->getConfiguration('prod', $website->getCode(), null) ?>

                            <?php foreach($this->getStoreGroups($website) as $group): ?>
                                <div class="section-config">
                                    <div class="entry-edit-head">
                                        <span><?php echo $this->__('Store Group') ?>: <?= $group->getName() ?></span>
                                    </div>
                                    <fieldset>
                                        <?php foreach($this->getStores($group) as $store): ?>
                                            <div class="section-config">
                                                <div class="entry-edit-head">
                                                    <span><?php echo $this->__('Store View') ?>: <?= $store->getName() ?></span>
                                                </div>
                                                <fieldset>
                                                    <strong>Stage:</strong>
                                                    <?php echo $this->getConfiguration('stage', $website->getCode(), $store->getCode()) ?>
                                                    <strong>Production:</strong>
                                                    <?php echo $this->getConfiguration('prod', $website->getCode(), $store->getCode()) ?>
                                                </fieldset>
                                            </div>
                                        <?php endforeach; ?>
                                    </fieldset>
                                </div>
                            <?php endforeach; ?>
                        </fieldset>
                    </div>
                <?php endforeach; ?>
            </fieldset>
        </div>
    </fieldset>
</div>
