<div class="section-config">
    <div class="entry-edit-head">
        <span><a href="#"><?php echo $this->__('Currently Used Configuration') ?></a></span>
    </div>
    <fieldset>
        <div class="section-config">
            <div class="entry-edit-head">
                <span><?php echo $this->__('Default') ?></span>
            </div>
            <fieldset>
                <strong><?php echo $this->__('Settings') ?>:</strong>
                <?php echo $this->getConfiguration(null, null) ?>
                
                <?php if($this->getFieldConfiguration('styla_connect/developer/is_developer_mode',null,null)): ?>
                    <div><strong><?php echo $this->__('Is in Developer Mode.') ?></strong></div>
                <?php endif ?>

                <?php foreach($this->getWebsites() as $website): ?>
                    <div class="section-config">
                        <div class="entry-edit-head">
                            <span><?php echo $this->__('Website') ?>: <?= $website->getName() ?></span>
                        </div>
                        <fieldset>
                            <strong><?php echo $this->__('Settings') ?>:</strong>
                            <?php echo $this->getConfiguration($website->getCode(), null) ?>
                            
                            <?php if($this->getFieldConfiguration('styla_connect/developer/is_developer_mode',$website->getCode(),null)): ?>
                                <div><strong><?php echo $this->__('Is in Developer Mode.') ?></strong></div>
                            <?php endif ?>

                            <?php foreach($this->getStoreGroups($website) as $group): ?>
                                <div class="section-config">
                                    <div class="entry-edit-head">
                                        <span><?php echo $this->__('Store Group') ?>: <?= $group->getName() ?></span>
                                    </div>
                                    <fieldset>
                                        <?php foreach($this->getStores($group) as $store): ?>
                                            <div class="section-config">
                                                <div class="entry-edit-head">
                                                    <span><?php echo $this->__('Store View') ?>: <?= $store->getName() ?></span>
                                                </div>
                                                <fieldset>
                                                    <strong><?php echo $this->__('Settings') ?>:</strong>
                                                    <?php echo $this->getConfiguration($website->getCode(), $store->getCode()) ?>
                                                    
                                                    <?php if($this->getFieldConfiguration('styla_connect/developer/is_developer_mode',$website->getCode(), $store->getCode())): ?>
                                                        <div><strong><?php echo $this->__('Is in Developer Mode.') ?></strong></div>
                                                    <?php endif ?>
                                                </fieldset>
                                            </div>
                                        <?php endforeach; ?>
                                    </fieldset>
                                </div>
                            <?php endforeach; ?>
                        </fieldset>
                    </div>
                <?php endforeach; ?>
            </fieldset>
        </div>
    </fieldset>
</div>
