<?php
/**
 * this is a copy of the normal Magento page/html/head.phtml, done to allow for selectively removing
 * the meta attributes, in case they're duplicated with the Styla's API SEO response.
 * 
 */

$seoResponseTags = Mage::helper('styla_connect')->getMagazineSeoTagNames();
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<?php if(!isset($seoResponseTags['title'])): ?><title><?php echo $this->getTitle() ?></title><?php endif; ?>
<?php if(!isset($seoResponseTags['meta-description'])): ?><meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" /><?php endif; ?>
<?php if(!isset($seoResponseTags['meta-keywords'])): ?><meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" /><?php endif; ?>
<?php if(!isset($seoResponseTags['meta-robots'])): ?><meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" /><?php endif; ?>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
