<?php
$website = Mage::app()->getRequest()->getParam('website');
$store = Mage::app()->getRequest()->getParam('store');
$isDeveloperMode = Mage::getStoreConfigFlag('styla_connect/developer/is_developer_mode', $store);
?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Styla Connect Assistant')?></h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span><?php echo $this->__('Send Login Data to Styla') ?></span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="edit_form" name="edit_form" method="post" action="<?=$this->getUrl('*/*/post')?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Your Styla User Login Data')?></h4>
        <fieldset id="my-fieldset">
            <div class="comment">
                <?php echo $this->__('The connect assistant will use your styla login to retrieve the necessary configuration data directly form styla.')?>
            </div>
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Your Styla Email')?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry validate-email" name="styla[email]" /></td>
                </tr>
                <tr>
                    <td class="label"><?=$this->__('Your Styla Password')?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" type="password" name="styla[password]" /></td>
                </tr>
                <?php if($isDeveloperMode): ?>
                <tr>
                    <td class="label"><?=$this->__('API Connection Url to Use')?></td>
                    <td class="input-ele"><input class="input-text" type="text" name="connection_url" value="<?= Styla_Connect_Model_Styla_Api_Oauth_Connector::STYLA_API_CONNECTOR_URL_PRODUCTION ?>" />
                    <div><?php echo $this->__('Note: If you leave this empty, the default [%s] url will be used.', Styla_Connect_Model_Styla_Api_Oauth_Connector::STYLA_API_CONNECTOR_URL_PRODUCTION) ?></div></td>
                </tr>
                <?php endif ?>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>
