<div class="section-config">
    <h2><?php echo $this->__('Please connect your Magento store to the Styla API.') ?></h2>
    <span><?php echo $this->__("If you haven't yet done so, please grant access to your Magento catalog by filling the form available here:") ?></span>
    <a target="_blank" href="<?php echo $this->getUrl('adminhtml/styla_api/index') ?>"><?php echo $this->__('Click here to go to the form.') ?></a>
</div>